ham_intermod/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hamim.urls'))
]

hamim/urls.py
from django.urls import path
from . import views
app_name = 'hamim'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # About page
    path('about/', views.about, name='about'),
    # HamIM version number and contact information
    path('basics/', views.basics, name='basics'),
    # How to Create a CSV page
    path('makecsv/', views.makecsv, name='makecsv'),
    # How to Manage Backup Channels page
    path('backups/', views.backups, name='backups')
]

hamim/models.py
from django.db import models

# Create your models here.

hamim/forms.py
from django import forms

class UploadFileForm(forms.Form):
    # label_equations = forms.BooleanField(required=False)
    file = forms.FileField()

hamim/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .im_analysis import analyze
from .forms import UploadFileForm

# Create your views here.
def index(request):
    """ The home page for HamIM """
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        print(form.errors.as_data())
        if form.is_valid():
            # Check if the checkbox is checked for labeling the equations
            label_equations = 'labeleqns' in request.POST
            uploaded_file = request.FILES['file'].read().decode('utf-8')
            # Analyze the frequencies in the CSV file for intermod and display
            # the analysis results
            analysis_results = analyze(uploaded_file, label_equations)
            context = {
                'analysis_results': analysis_results
            }
            return render(request, 'hamim/upload_success.html', context)
    else:
        form = UploadFileForm()
    return render(request, 'hamim/index.html', {'form': form})

def about(request):
    """ HamIM version number and contact information """
    return render(request, 'hamim/about.html')

def makecsv(request):
    """ Teach the user how to make a CSV file """
    return render(request, 'hamim/makecsv.html')

def basics(request):
    """ Tell the user something about HamIM and how to use it """
    return render(request, 'hamim/basics.html')

def backups(request):
    """ Teach the user how to manage backup channels """
    return render(request, 'hamim/backups.html')

hamim/templates/hamim/about.html
{% extends "hamim/base.html" %}
{% load static %}  <!-- Load static folder with images in it. -->

{% block page_header %} 
  <div class="jumbotron">
    <h1 class="display-3">About HamIM</h1>
    <p>
      HamIM Version: Jan 17, 2025</p>
    <p>
      <h2>Known Problems & Solutions:</h2>
      <ol class="list-group">
        <li class="list-group-item"><b>Problem:</b> If every channel is identified as a backup
          channel, then execution will fail with <b>Server Error 500</b>.<br>
          <b>Workaround:</b> Add a dummy simplex channel with a frequency that
          won't cause IMD. Leave the Backups column blank for the dummy channel.
          <br><b>For example:</b> RxFreq=999, TxFreq= , Backups= , Label=Dummy</li> 
        </li>
      </ol>
    </p>
    <p class="small">
      Send questions and comments to:
      <i><a href="mailto:Scott.Bordelon@gmail.com">Scott.Bordelon@gmail.com</a></i>
    </p>
  </div>
  {% endblock page_header %}

hamim/templates/hamim/backups.html
{% extends "hamim/base.html" %}
{% load static %}  <!-- Load static folder with images in it. -->

{% block page_header %} 
  <div class="jumbotron">
    <h1 class="display-3">Managing backup channels</h1>
    <p class="lead">
      Radio channel plans often include backup channels to serve as a redudant
      channel alternative in case a primary channel is unusable. 
    </p>
    <p class="lead">
      When checking your channel plan for IMD, backup channels can unnecessarily
      increase the likelihood of causing IMD because the backup channel will
      never get used simultaneously with the primary channel. If HamIM were to
      compute an IMD conflict caused by interaction between a primary channel
      and its backup, that would be a conflict that can be ignored. That might
      not be so tragic if your plan only has a single backup channel, but
      complex plans may have have 12 or more backup channels, dramatically
      increasing the odds of reporting an IMD conflict that may never occur
      in reality. One way to manage this burden is to submit numerous plans
      into HamIM where each plan only includes a single backup or primary
      channel. Take this channel plan for example:
      <center><figure class="figure">
        <img src="{% static 'CSVExample_1backup.png' %}" class="shadow mb-2">
        <figcaption class="figure-caption">
          Channel plan with one backup channel, Command Backup
        </figcaption>
      </figure></center>
    </p>
    <p class="lead">
      The channels labeled "Command Primary" and "Command Backup" will never be
      used at the same time. You'll either be using the Primary channel or the
      Backup channel at your event but not both at the same time. You've
      essentially got two channel plans -- one with "Command Primary" and
      another one with "Command Backup", so to avoid reporting IMD caused by
      channel interactions that will never happen, split your channel plan
      into two channel plans, and run HamIM on each. In the example, split
      the channel plan into two plans as illustrated below:
      <center><figure class="figure">
        <img src="{% static 'CSVExample_1backup_split.png' %}">
        <figcaption class="figure-caption">
          Channel plan with one backup channel, split into two channel plans
        </figcaption>
      </figure></center>
    </p>
    <p class="lead">
      If your channel plan has more than one channel with corresponding backup
      channels, you'll need to create multiple channel plans to
      accomodate all possible combinations of backup channel options. Take for
      example, a plan with two primary channels (Command Primary and Tactical
      Primary), where Command Primary has a single backup channel and Tactical
      Primary has two backup channels. To accomodate all possible combinations
      of primary and backup channels, this plan needs to be split into six plans
      as follows:
    </p>
    <center><figure class="figure">
      <img src="{% static 'CSVExample_2primaries_split.png' %}">
      <figcaption class="figure-caption">
        Channel plan with two primary channels with backups, split into six channel plans
      </figcaption>
    </figure></center>
    <p class="lead">
      Note that the two potential Command channels multiplied by the three
      potential Tactical channels, results in six derivative plans. The number
      of derivative plans will be the total product of the number of the backup
      channels with its primary multiplied by each other primary channel with
      its backups in the original plan. For a plan with a large number of
      primary and backup channels, creating the derivative plans can be a huge
      burden.
    </p>
    <p class="lead">
      HamIM will automatically generate the derivative plans and run them if you
      indicate which channels are backups in the CSV file. Simply add a column
      named "Backups" to the CSV file, and assign an arbitrary name to the
      channels participating in the gang of backup channels with its primary
      channel. In the example below, a Backups column has been added with tags
      indicating the primary Command and Tactical channels have corresponding
      backup channels.
    </p>
    <a href="{% static 'CSVExample_Backups.csv' %}" download>
      <center><figure class="figure">
        <img src="{% static 'CSVExample_Backups.png' %}" class="shadow mb-2">
        <figcaption class="figure-caption">
          Example CSV file with "Backups" column
        </figcaption>
      </figure></center>
    </a>
    <p class="lead">
      That's all you need to do. Now just upload your new CSV file. HamIM
      will automatically generate and run all combinations of derivative channel
      plans.
    </div>
  {% endblock page_header %}

hamim/templates/hamim/base.html
{% load bootstrap4 %}
{% load static %}  <!-- Load static folder with images in it. -->

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>HamIM</title>

  {% bootstrap_css %} 
  {% bootstrap_javascript jquery='full' %}
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'hamim:index'%}">
    <img src="{% static 'GEAH.png' %}" height="75"> HamIM
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarCollapse" aria-controls="navbarCollapse"
      area-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
            How to Run HamIM
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'hamim:basics'%}">The Basics</a>
            <a class="dropdown-item" href="{% url 'hamim:backups'%}">Backup Channels</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'hamim:makecsv'%}">How to Make a CSV File</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'hamim:about'%}">
            About
          </a>
        </li>
      </ul>
    </div>
  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>

</html>

hamim/templates/hamim/basics.html
{% extends "hamim/base.html" %}
{% load static %}  <!-- Load static folder with images in it. -->

{% block page_header %} 
  <div class="jumbotron">
    <h1 class="display-3">How to run HamIM</h1>
    <p class="lead">
      HamIM is a webapp to compute intermodulation distortion (IMD)
      conflicts, given a list of radio frequencies to be used at an event.</p>
    <p class="lead">
      The only input is a CSV file with two columns listing the frequencies
      planned for your event. The column headers must include "RxFreq" and
      "TxFreq" for your receiving and transmitting frequencies, respectively.
      For repeater channels, the TxFreq column can use the shorthand notation
      "+" or "-" to indicate your repeater offset direction, and HamIM will
      compute the transmit frequency. For simplex channels, the TxFreq column
      can remain blank. In the example below, the column labeled "Label" is
      optional, but labels help make the report more readable. Any other columns
      will be ignored.
      <a href="{% static 'CSVExample.csv' %}" download>
        <center><figure class="figure">
          <img src="{% static 'CSVExample.png' %}" class="shadow mb-2">
          <figcaption class="figure-caption">Example CSV file</figcaption>
        </figure></center>
      </a>
    </p>
    <p class="lead">
      HamIM will generate its report immediately after the CSV file is uploaded.
      The "Hit Scores" summary at the end of the report identifies which radio
      frequencies participated in some form of IMD, and the TOTAL SCORE indicates
      how often they participated. Those frequencies with the highest scores
      are the ones causing the most trouble, so those are the frequencies you
      should focus on changing. If a frequency has a score of 0, it is not
      included in the hit scores summary. Continue tweaking your radio
      frequencies until there are no more identified in the list.
    </p>
  </div>
  {% endblock page_header %}

hamim/templates/hamim/index.html
{% extends "hamim/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Find your IMD.</h1>
    <p class="lead">HamIM analyzes your list of radio frequencies for potential
      intermod distortion (IMD). Simply upload a CSV file with your radio
      frequencies.
    </p>
  </div>
{% endblock page_header %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h5>Options</h5>
    <input type="checkbox" name="labeleqns" id="labelEquations">
    <label  for="labelEquations">
      Label frequencies in report equations?
    </label>
    <br><br>
    <h5>CSV file upload</h5>
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Upload</button>
  </form>
{% endblock content %}

hamim/templates/hamim/makecsv.html
{% extends "hamim/base.html" %}
{% load static %}  <!-- Load static folder with images in it. -->

{% block page_header %} 
  <div class="jumbotron">
    <h1 class="display-3">How to make a CSV file</h1>
    <p class="lead">
      A CSV (Comma-Separated Values) file is a plain text file for storing a
      table (rows and columns) of data. Each line in a CSV file represents a
      row of data in your table. Every line of text in the CSV file is separated
      by the same number of commas to represent columns of text in your table.
    </p>
    <p>
      For example, say you want to create a CSV file for the following table
      with 4 rows and 3 columns:
      <center><table class="table table-bordered">
        <thead>
        <tr class="table-primary">
          <th class="border border-dark"><h5><center>RxFreq</center></h5></th>
          <th class="border border-dark"><h5><center>TxFreq</center></h5></th>
          <th class="border border-dark"><h5><center>Label</center></h5></th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td class="border border-dark"><center>145.27</center></td>
          <td class="border border-dark"><center>-</center></td>
          <td class="border border-dark"><center>W6ASH</center></td>
        </tr>
        <tr>
          <td class="border border-dark"><center>147.485</center></td>
          <td class="border border-dark"></td>
          <td class="border border-dark"><center>Staging</center></td>
        </tr>
        <tr>
          <td class="border border-dark"><center>144.67</center></td>
          <td class="border border-dark"><center>446.5</center></td>
          <td class="border border-dark"><center>Crossband Uplink</center></td>
        </tr>
        </tbody>
      </table></center>
      Since a CSV file is just a plain text file, there are numerous ways to
      create it. I'll illustrate three of the most common ways.
      <br><br>
      <h3><u>1. Use a Text Editor</u></h3>
      Every computer has a text editor available. <b>Notepad</b> is the default
      text editor in Windows. MacOS has <b>TextEdit</b>. Linux has <b>vi</b>.
      Run your favorite text editor and start typing your rows of data with
      columns separated by commas. For the example above, you should get
      something like this:
      <a href="{% static 'TE_CSVExample.txt' %}" download>
        <center><figure class="figure">
          <img src="{% static 'TE_CSVExample.png' %}" class="shadow mb-2">
          <figcaption class="figure-caption">Example CSV file typed into Notepad</figcaption>
        </figure></center>
      </a>
      Note the following:<ul>
        <li>Our table has 4 rows so our CSV file has 4 lines.</li>
        <li>Our table has 3 columns so every line in our CSV file has 2 commas,
          making 3 columns per row.</li>
        <li>The first (header) line has no formatting (such as bold text).</li>
        <li>The columns in our text file aren't necessarily lined up. That's
          okay.</li>
        <li>The third line has 2 commas next to each other because the second
          column in that row is an empty cell.</li>
        <li>The last line has text with whitespace, "Crossband Uplink". The
          whitespace does NOT create a new column. Columns are only separated by
          commas.</li>
      </ul>
      Now save your file as a plain text file type. Do NOT save your file as a
      file type that supports additional formatting (bold, italic, etc.) such as
      Rich Text Format (RTF) or Word (DOC or DOCX). Either .txt or .csv are
      common filename extensions to use, but HamIM doesn't care what filename
      extension you use.
      <br><br>
      <h3><u>2. Use Microsoft Excel (or LibreOffice Calc)</u></h3>
      If you're familiar with using <b>Microsoft Excel</b>, you can use it to
      create a CSV file. After you type your table into <b>Excel</b>, it will
      look something like this:
      <a href="{% static 'MSE_CSVExample.csv' %}" download>
        <center><figure class="figure">
          <img src="{% static 'MSE_CSVExample.png' %}" class="shadow mb-2">
          <figcaption class="figure-caption">Example CSV file typed into Microsoft Excel</figcaption>
        </figure></center>
      </a>
      Save your file as a "CSV (Comma delimeted) (*.csv)" file type. Do NOT
      save it as "CSV <b>UTF-8</b> (Comma delimited) (*.csv)" or "Excel Workbook
      (.xlsx)" or any other richly formatted file types.
      <br><br>
      <b>NOTE:</b> If you don't have access to Microsoft Excel,
      <a href="https://www.libreoffice.org/discover/calc/" target="_blank">
      <b>LibreOffice Calc</b></a> is an open source alternative to Microsoft
      Excel that's free to download and use on Windows, macOS, and Linux.
      <br><br>
      <h3><u>3. Use Google Sheets</u></h3>
      <a href="https://www.google.com/sheets/about/" target="_blank"><b>Google Sheets</b></a> is like <b>Microsoft Excel</b>, except it's web-based
      and free to use. After you type your table into <b>Sheets</b>, it will
      look something like this:
      <a href="https://docs.google.com/spreadsheets/d/1E6z3Cu7F_1yOD7d9okivmpojH4vMWKNkWvv55VAKxNs/edit?usp=sharing" target="_blank">
        <center><figure class="figure">
          <img src="{% static 'GS_CSVExample.png' %}" class="shadow mb-2">
          <figcaption class="figure-caption">Example CSV file typed into Google Sheets</figcaption>
        </figure></center>
      </a>
      Save it to your computer using the <b>File</b> pulldown menu option,
      <b>Download > Comma Separated Values (.csv)</b>.
    </p>
  </div>
  {% endblock page_header %}

hamim/templates/hamim/upload_success.html
{% extends "hamim/base.html" %}

{% block content %}
  {{ analysis_results | safe | linebreaks }}
{% endblock content %}